### PR TITLE
Upgrade terraform-provider-grafana to v3.2.0

### PR DESCRIPTION
**Pull request by ImTomEddy**
This PR upgrades the terraform-provider-grafana package from `v2.19.1` to `v3.2.0` this includes breaking changes with the removal of deprecated resources

- `grafana_api_key`
- `grafana_cloud_stack_api_key`
- `grafana_cloud_api_key`
- `grafana_oncall_action`

There are other breaking changes included in the terraform-provider-grafana changelogs https://github.com/grafana/terraform-provider-grafana/releases/tag/v3.0.0.

### CODE REVIEW

**Comment by ringods** [comment]
@ImTomEddy I will not yet merge this PR. The last merge I did was putting the resources into modules, but no release has been created with this in place.

We are currently on major v0 using v2 of the upstream TF provider. Semantic versioning wise, I'm allowed to make breaking changes, which I also want to do now. My idea was bumping this provider to v1 when we take in v3 of the upstream TF provider.

What do you think?

**Comment by ImTomEddy** [comment]
> We are currently on major v0 using v2 of the upstream TF provider. Semantic versioning wise, I'm allowed to make breaking changes, which I also want to do now. My idea was bumping this provider to v1 when we take in v3 of the upstream TF provider.

I was actually thinking about versioning of this package while raising the PR. With v0 the statement is that things may change at anytime and it is an unstable package. Which I don't believe is a true sentiment anymore. I personally run this in production and the only issues I've had are caused by my implementation on the package.

As a bump to v3 will contain multiple breaking changes, I think it is the ideal time to promote the package to v1. If the module change is also a breaking change (I'm still not too versed in pulumi packages - I'm just the upgrade guy 😆) this could be the opportunity to leave v0 in an easy to upgrade state and bundle all the breaking changes into a single v1 release.

**Comment by ringods** [comment]
@ImTomEddy indeed, let's bring everything in and go for a v1, built against upstream TF provider v3.

**Comment by ImTomEddy** [comment]
> @ImTomEddy indeed, let's bring everything in and go for a v1, built against upstream TF provider v3.

@ringods Everything is already brought in, I forked off from the modules change and then built with the upstream v3 provider 😄

**Review by ringods — APPROVED** [review]

**Comment by ringods** [comment]
@ImTomEddy if you want to co-maintain, please create a PR in https://github.com/pulumiverse/infra adding a file for yourself here:

https://github.com/pulumiverse/infra/tree/main/03-members

The Pulumiverse board will review that PR. With access rights in place, you don't have to fork this repo any longer.

**Comment by ImTomEddy** [comment]
> @ImTomEddy if you want to co-maintain, please create a PR in https://github.com/pulumiverse/infra adding a file for yourself here:
> 
> https://github.com/pulumiverse/infra/tree/main/03-members
> 
> The Pulumiverse board will review that PR. With access rights in place, you don't have to fork this repo any longer.

@ringods I'll have a look! I've definitely been considering trying to help more, but I'm still not the most familiar with how the package ecosystem works.

Do you have any good reference material I can use to improve my knowledge and then feel more comfortable with the idea?

**Pull request merged**
